// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace nguyenvankhoat591.Migrations
{
    [DbContext(typeof(MvcNVK591Context))]
    partial class MvcNVK591ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("nguyenvankhoat591.Models.CompanyNVK591", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyNVK591");
                });

            modelBuilder.Entity("nguyenvankhoat591.Models.NVK0591", b =>
                {
                    b.Property<string>("NVKId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NVKGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NVKName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NVKId");

                    b.ToTable("NVK0591");
                });
#pragma warning restore 612, 618
        }
    }
}
